// TestDaF Configuration
// Generated from top_200_exam_universe_seed.csv

export const EXAM_CONFIG = {
  examId: "EXAM025",
  slug: "testdaf",
  name: "TestDaF",
  fullName: "TestDaF",
  alias: "TestDaF",
  family: "TestDaF",
  category: "Language proficiency",
  subcategory: "German for study",
  country: "Global",
  region: "Global",
  languages: ["German"],
  estimatedAnnualTakers: "varies",
  testingWindow: "Scheduled sessions",
  schedulePattern: "Several dates/year",
  ageGroup: "17-35",
  targetUser: "Study abroad candidate",
  delivery: "Digital/paper mix",
  questionTypes: ["Reading","listening","writing","speaking"],
  adaptivity: "Linear",
  sections: "4 skills",
  scoringMode: "Levels",
  essayOrSpeaking: "Speaking + writing",
  ipRisk: "Medium",
  contentReuse: "language_4skills",
  uiEngine: "4skills_study_abroad",
  monetizationPotential: "Medium",
  tier: "Tier 4",
  launchWave: "Wave 6",
  themeColor: "#059669",
  themeColorDark: "#047857",
  localizationComplexity: "Medium",
  offlineNeeded: false,
  mobileFirst: false,
  locale: "de",
  isRTL: false,
  freemiumGate: {
    dailyQuestions: 10,
  },
} as const;

export type ExamConfig = typeof EXAM_CONFIG;
